export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000/api';

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    PROFILE: '/auth/profile',
    ME: '/auth/me',
    CHANGE_PASSWORD: '/auth/change-password',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  USERS: {
    BASE: '/users',
    BY_ID: (id) => `/users/${id}`,
    SEARCH: '/users/search',
    STATISTICS: '/users/statistics',
    COURSES: (id) => `/users/${id}/courses`,
    PROGRESS: (id) => `/users/${id}/progress`,
    DASHBOARD: (id) => `/users/${id}/dashboard`,
  },
  COURSES: {
    BASE: '/courses',
    BY_ID: (id) => `/courses/${id}`,
    POPULAR: '/courses/popular',
    SEARCH: '/courses/search',
    MY_COURSES: '/courses/my-courses',
    LESSONS: (id) => `/courses/${id}/lessons`,
    QUIZZES: (id) => `/courses/${id}/quizzes`,
    ENROLL: (id) => `/courses/${id}/enroll`,
    UNENROLL: (id) => `/courses/${id}/unenroll`,
    RATE: (id) => `/courses/${id}/rate`,
    RATINGS: (id) => `/courses/${id}/ratings`,
    STUDENTS: (id) => `/courses/${id}/students`,
    ANALYTICS: (id) => `/courses/${id}/analytics`,
  },
  LESSONS: {
    BASE: '/lessons',
    BY_ID: (id) => `/lessons/${id}`,
    BY_COURSE: (courseId) => `/lessons/course/${courseId}`,
    PROGRESS: (id) => `/lessons/${id}/progress`,
    COMPLETE: (id) => `/lessons/${id}/complete`,
    NEXT: (id) => `/lessons/${id}/next`,
    PREVIOUS: (id) => `/lessons/${id}/previous`,
    CAN_ACCESS: (id) => `/lessons/${id}/can-access`,
    CURRENT: (courseId) => `/lessons/course/${courseId}/current`,
  },
  QUIZZES: {
    BASE: '/quizzes',
    BY_ID: (id) => `/quizzes/${id}`,
    BY_COURSE: (courseId) => `/quizzes/course/${courseId}`,
    BY_LESSON: (lessonId) => `/quizzes/lesson/${lessonId}`,
    TAKE: (id) => `/quizzes/${id}/take`,
    ATTEMPTS: (id) => `/quizzes/${id}/attempts`,
    CAN_TAKE: (id) => `/quizzes/${id}/can-take`,
    STATISTICS: (id) => `/quizzes/${id}/statistics`,
  },
  PROGRESS: {
    BASE: '/progress',
    BY_LESSON: (lessonId) => `/progress/lesson/${lessonId}`,
    BY_COURSE: (courseId) => `/progress/course/${courseId}`,
    SUMMARY: (courseId) => `/progress/course/${courseId}/summary`,
    COMPLETE: '/progress/complete',
    NEXT_LESSON: (courseId) => `/progress/course/${courseId}/next-lesson`,
    STATISTICS: '/progress/statistics',
    RECENT_ACTIVITY: '/progress/recent-activity',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard',
    USERS: '/admin/users',
    COURSES: '/admin/courses',
    STATISTICS: '/admin/statistics',
  },
};
